### ISSUE TITLE
How do you secure manager with provided SSL certs

### ISSUE THREAD

**Issue by artisticcheese** [pscripted/cDSCDockerSwarm#2]
Can this DSC resource to accept certificates which can be used for swarm manager initialization?

**Comment by pscripted** [comment]
Are you referring to to securing the daemon endpoint with TLS? or if there is an existing cert being used on a daemon of an existing manager. At the moment the only TLS support is through the use of the CA service the DSC module will spin up that will enroll all the endpoints in TLS. It does not support external certificates at the moment.

**Comment by artisticcheese** [comment]
Would be great an option to pass your own certs obviously for initialisation

**Comment by pscripted** [comment]
thinking about it further, if you drop:
$env:ALLUSERSPROFILE\docker\certs.d\cert.pem
$env:ALLUSERSPROFILE\docker\certs.d\key.pem

with a file resource before this resource is called, and you have TLS set to enabled in this resource it will enable TLS on the daemon using that cert.

**Comment by artisticcheese** [comment]
Ok will try to use that.
I'm planning to use this module for swarm ARM template in Azure and trying to figure out whether it will work as intended with key information being stored in KeyVault. I plan to use VMSS (virtual machine scale sets) and looks all pieces are there to make it happen. Did you use this module for any sort of Azure based roll out?

**Comment by artisticcheese** [comment]
I'm trying to figure out how to avoid chicken and egg situation with docker swarm resource. It requires to provide information for existing swarm manager, but how to deal with situation when entire solution is not deployed yet and first node in fact shall become manager and IP address of that member shall be used as swarm IP for other nodes to join

**Comment by pscripted** [comment]
The IP of the swarm master can work 2 ways. You can provide an external master that already exists, and the nodes the resource will join against it. Or, provide the IP of one of the nodes receiving the DSC push; a node as fresh as any other -- When the node running it finds it is supposed to be the master it will init the swarm. The other nodes (in accounting for this delay) will retry their join a few times so the swarm should come up on the first run of the config.

**Comment by artisticcheese** [comment]
So DSC code is smart enough that for node which is designated to be a first swarm manager but yet not initilialized to match IP of node to IP in DSC configuration and realize that it's designated to be first manager and do `docker swarm init`?
What happens if I reimage box from scratch and it initializes new swarm, what happens to other workers etc?

**Comment by pscripted** [comment]
Correct. The master IP in the config is used initially as the node to initialize the swarm (or join against), and for other nodes verify their membership to the correct swarm (they verify that IP is a manager in the swarm they are in). If that IP were no longer a manager in the swarm the other nodes would assume they are in the wrong swarm and attempt to join against that IP again.  So if you removed that IP/node from the swarm, but left it in the config the nodes would not be happy. 

If you wanted to remove that original node from the swarm, the master IP can be changed in the config to any node that would be remaining an active manager in the swarm.

**Comment by artisticcheese** [comment]
So if original IP was reinitialized from scratch since image was rebuilt and hence new swarm was formed, the other nodes will disjoin original swarm they were in and connect to a new swarm?

**Comment by pscripted** [comment]
yes, that is how it should work. the original node would need to me demoted/removed from the swarm though, as if it was re-imaged while in the swarm its IP would remain in the manager raft, and nodes would think it's the right swarm, just that node is offline.

**Comment by artisticcheese** [comment]
Well that's the problem. What happens if original node is not demoted/removed properly and just starts from scratch with DSC resource and initializes itself to be a new swarm since it knows it's a first node in swarm? What happens to other node managers which are still part of old swarm? Will they leave it and rejoin a new swarm or they will be forever unhappy?

**Comment by pscripted** [comment]
It's the trade off of wanting to dynamically create and join the swarm vs individual nodes only aware of their own configuration. No single node is aware of the quorum without a single point to refer to, hence the dedicated master IP. The only way around it I can think of would be have a manager external to the DSC configuration (or with its own configuration) so that it is always the trusted source of truth on the state of quorum for the swarm.
