### ISSUE TITLE
Need option to have swarm manager in `drain` mode

### ISSUE THREAD

**Issue by artisticcheese** [pscripted/cDSCDockerSwarm#4]
Hello,

How do I dedicate specific manager to be in `drain` mode. Reason being that I want to have original swarm manager on separate network and managed as a `pet` as opposed to rest of swarm managers and works which will be managed as `cattle`. I don't think it's possible to do with `daemon.json`.

**Comment by pscripted** [comment]
Can't at the moment, sounds like a good addition.  I think a separate node availability resource may be best, as that will be the most flexible for individual nodes. without cluttering up the configuration too much.
